In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.pandas.set_option("display.max_columns",None)

In [30]:
from sklearn.datasets import fetch_california_housing

In [33]:
housing = fetch_california_housing()

In [34]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [35]:
dataset =pd.DataFrame(housing.data)

In [36]:
dataset


0     1         2         3       4         5      6       7
0      8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1      8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2      7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3      5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4      3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25
...       ...   ...       ...       ...     ...       ...    ...     ...
20635  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
20636  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
20637  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
20638  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
20639  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

[20640 rows x 8 columns]

In [37]:
dataset.columns = housing.feature_names

In [38]:
dataset.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [39]:
x = dataset
y = housing.target

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
regression = LinearRegression()

In [44]:
regression.fit(x_train,y_train)

LinearRegression()

In [45]:
pred = regression.predict(x_test)

In [48]:
pred


array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133])

In [49]:
y_test

array([0.477  , 0.458  , 5.00001, ..., 2.184  , 1.194  , 2.098  ])

In [52]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [55]:
print(f"MSE: {mean_squared_error(y_test,pred)}")
print(f"MAE : {mean_absolute_error(y_test,pred)}")
print(f"RMSE : {np.sqrt(mean_squared_error(y_test,pred))}")

MSE: 0.5305677824766758
MAE : 0.5272474538305952
RMSE : 0.7284008391515456


In [57]:
#standardizing the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [58]:
from sklearn.linear_model import LinearRegression

In [59]:
stand_regression = LinearRegression()

In [60]:
stand_regression.fit(x_train,y_train)

LinearRegression()

In [61]:
std_pred = stand_regression.predict(x_test)

In [62]:
std_pred

array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133])

In [63]:
print(f"MSE: {mean_squared_error(y_test,std_pred)}")
print(f"MAE : {mean_absolute_error(y_test,pred)}")
print(f"RMSE : {np.sqrt(mean_squared_error(y_test,std_pred))}")

MSE: 0.5305677824766758
MAE : 0.5272474538305952
RMSE : 0.7284008391515456


In [ ]:
0.5305677824766758
MAE : 0.5272474538305952
RMSE : 0.7284008391515456