In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [12]:
pip install category_encoders

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 966.5 kB/s eta 0:00:00


In [13]:
import category_encoders as ce

#Dataset

In [3]:
data = pd.read_csv("/content/drugs.csv")

# Data preprocessing

In [4]:
df = data.copy()

In [6]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [8]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [14]:
encoaded = ce.OrdinalEncoder(cols=[feature for feature in df.columns if df[feature].dtype == "O"]).fit_transform(df)
encoaded.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    1   1            1   25.355     1
1   47    2   2            1   13.093     2
2   47    2   2            1   10.114     2
3   28    1   3            1    7.798     3
4   61    1   2            1   18.043     1

In [16]:
encoaded.Cholesterol.unique()

array([1, 2])

In [17]:
encoaded.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

# independent and dependent feature split

In [18]:
# independent feature
x = encoaded.drop("Drug",axis=1)
# dependent feature
y = encoaded["Drug"]

# train test split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# randomforestclassifier

In [20]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [23]:
model.predict(x_test)

array([3, 1, 3, 2, 1, 1, 1, 3, 4, 3, 4, 3, 1, 4, 5, 1, 5, 3, 2, 1, 5, 3,
       3, 1, 1, 1, 2, 3, 1, 3, 1, 2, 2, 1, 4, 1, 3, 4, 1, 4])

# model evaluation

In [26]:
accuracy = accuracy_score(y_test,model.predict(x_test))
clasif_report = classification_report(y_test,model.predict(x_test))
confusion_mat = confusion_matrix(y_test,model.predict(x_test))

In [31]:
print("accuracy :-", accuracy)
print("clasif_report :-", clasif_report)
print("confusion_mat :-", confusion_mat)

accuracy :- 1.0
clasif_report :-               precision    recall  f1-score   support

           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         3

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

confusion_mat :- [[15  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0 11  0  0]
 [ 0  0  0  6  0]
 [ 0  0  0  0  3]]
